cmake_minimum_required(VERSION 4.1)
project(CPP)

set(CMAKE_CXX_STANDARD 20)

add_executable(CPP main.cpp
        Assignment/Odd'n'even.cpp
        Assignment/Multipication_Table.cpp
        Countdown.cpp
        Assignment/Rectangle.cpp
        ClassPrac/main.cpp
        ClassPrac/main2.cpp
        ClassPrac/block.cpp
        brocode.cpp
        brocode.cpp
        brocode2.cpp
        RandomgenpseudorandomNum.cpp
        number_guessingLoop.cpp
        FunctionHBD.cpp
        Assignment/Arrayreverse.cpp
        Assignment/Even_Odd_Array.cpp
        Assignment/Number_small_Array.cpp
        Assignment/Arrayreverse.cpp
        Assignment/3by3_Array_Matrix.cpp
        Assignment/Array_Sort_Ascend.cpp
        ClassPrac/main3.cpp
        Assignment/Market_Receipt.cpp
        "Assignment/Student_Record .cpp"
        Function.cpp
        Assignment/Array_Reverse_Search_spaceRemoval.cpp
        Assignment/Array_Reverse_Search_spaceRemoval.cpp
        returnkey_word.cpp
        Function_Newname_Concat.cpp
        Function_Overloading.cpp
        Function_banking.cpp
        Function_Rock_paper_scissors.cpp
        Array.cpp
        sizeOF_operator.cpp
        Array_iterate_element.cpp
        ForEach_Loop.cpp
        Array_search_num.cpp
        ClassPrac/obj.cpp
        ClassPrac/si_oop.cpp
        ClassPrac/inheritance.cpp
        ClassPrac/encapsulation.cpp
        Array_bubble_sort.cpp
        "Fill_function .cpp"
        AcceptingUserio_Array.cpp
        multidimensional_array.cpp
        Array_question.cpp
        Memory_address.cpp
        ClassPrac/fileHandling.cpp
        "file handle/fileHandling.cpp"
        "file handle/fileHanling_ifstream_02.cpp"
        "file handle/fileHanling_ifstream_02.cpp"
        "file handle/fileHanling_ifstream_02.cpp"
        Const_Parameters.cpp
        Pass_reference&Pass_value.cpp
        luhnAlgorithm_calculator.cpp
        Pointer/pointers.cpp
        Pointer/Null_Values.cpp
        Pointer/tic_tacToe.cpp
        ud/Dynamic_memory.cpp
        ud/Recursion.cpp
        "ud/Function_Templates .cpp"
        ud/structs.cpp
        " Pass_Structs_as_Arguments.cpp"
        ud/Enums.cpp
        ud/OOP.cpp
        ud/constructors.cpp
        ud/Constructor_Overloading.cpp
        " Getters_Setters.cpp"
        ud/innheritance.cpp)
